[versions]
libphonenumber = "9.0.23"
geocoder = "3.23"
josmCompile = "19439"
minJosm = "17428"
josmGradlePlugin = "0.8.2"
javaLauncher = "21"
javaTarget = "17"

[libraries]
libphonenumber = { group = "com.googlecode.libphonenumber", name = "libphonenumber", version.ref = "libphonenumber" }
geocoder = { group = "com.googlecode.libphonenumber", name = "geocoder", version.ref = "geocoder" }

[plugins]
josm = { id = "org.openstreetmap.josm", version.ref = "josmGradlePlugin" }
